### ISSUE TITLE
peka2.tv: коменты к статьям

### ISSUE THREAD

**Issue by storage627** [Hukutoss/sc2tvnotificator-js#3]
Ссылка на комментарии к статье выводится в виде comments/article/123 по которой непонятно, что за статья (и сама ссылка нерабочая).

**Comment by NickKush** [comment]
Fixed in 0.5.0

**Comment by storage627** [comment]
По статьям хз, но есть еще такие же каменты под стримами и с ними такая же фигня, только в виде comments/stream/123

**Comment by NickKush** [comment]
Forgot about stream comments. Fixed 0.5.1
